name: ntblcp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter:
    sdk: flutter
  syncfusion_flutter_datagrid: ^25.1.35
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  amplify_api: ^1.7.0
  amplify_flutter: ^1.7.0
  amplify_core: ^1.7.0
  http: ^1.2.1
  badges: ^3.1.2
  another_flushbar: ^1.12.30
  pluto_grid: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
